services:
  # Web Service
  - type: web
    name: django-file-upload
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DATABASE_URL
        fromDatabase:
          name: django_db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: django_db
    databaseName: django_file_upload_db
    user: django_user
    plan: free
